FitZone/src/Entity/PRESENTATION.php
<?php

namespace App\Entity;

use App\Repository\PRESENTATIONRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PRESENTATIONRepository::class)]
class PRESENTATION
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Texte = null;

    #[ORM\Column(length: 255)]
    private ?string $Photo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntroduction(): ?string
    {
        return $this->Introduction;
    }

    public function setIntroduction(string $Introduction): static
    {
        $this->Introduction = $Introduction;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->Texte;
    }

    public function setTexte(string $Texte): static
    {
        $this->Texte = $Texte;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(string $Photo): static
    {
        $this->Photo = $Photo;

        return $this;
    }
}

FitZone/src/Controller/PresentationController.php
<?php

namespace App\Controller;

use App\Entity\PRESENTATION;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class PresentationController extends AbstractController
{
    #[Route('/presentation', name: 'app_presentation')]
    public function index(EntityManagerInterface $em): Response
    {
        $presentation = $em->getRepository(PRESENTATION::class)->findOneBy(['id' => 1]);
        return $this->render('presentation/index.html.twig', [
            'presentation' => $presentation,
        ]);
    }
    #[Route('/presentation/modification', name: 'app_presentation_modification')]
    public function modifi(EntityManagerInterface $em): Response
    {
        $presentation = $em->getRepository(PRESENTATION::class)->findOneBy(['id' => 1]);
        return $this->render('presentation/modifierPresentation.html.twig', [
            'presentation' => $presentation,
        ]);
    }
    #[Route('/presentation/modifier', name: 'app_presentation_modifier')]
    public function modifier(Request $request, EntityManagerInterface $em): Response
    {
        echo $request->request->get('intro');
        $intro = $request->request->get('intro');
        $text = $request->request->get('text');
        $image = $request->request->get('image');
        $presentation = $em->getRepository(PRESENTATION::class)->findOneBy(['id' => 1]);
        $presentation->setIntroduction($intro);
        $presentation->setTexte($text);
        $presentation->setPhoto($image);
        $em->persist($presentation); //$em->remove($article) //persist
        $em->flush();
        return $this->redirectToRoute('app_accueil');
    }
}

FitZone/templates/presentation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Presentation{% endblock %}

{% block body %}
</style>
<div class="titre-Accueil">
<h1>Présentation</h1>
</div>
{% if app.user and is_granted('ROLE_ADMIN') %}
<div class='posterAvis'>
<form method="POST" action="/presentation/modification">
    <input type="submit" value="Modifier">
</form>
{% endif %}
</div>
<div class="presentation">
<div class="imag">
<img src={{presentation.photo}} alt="une image">
</div>
<div class="introduction">
<p>{{presentation.introduction}}</p>
</div>
<div class="text"><br>
<p>{{presentation.texte}}</p>
</div></div>
{% endblock %}

FitZone/templates/presentation/modifierPresentation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Presentation{% endblock %}

{% block body %}
</style>
<div class="titre-Accueil">
<h1>Présentation</h1>
</div>
{% if app.user and is_granted('ROLE_ADMIN') %}
<form class="presentation" method="POST" action="/presentation/modifier">
<div class="imag">
<p><textarea id="image" name="image">{{presentation.photo}}</textarea></p>
</div>
<div class="introduction">
<p><textarea id="intro" name="intro">{{presentation.introduction}}</textarea></p>
</div>
<div class="text"><br>
<p><textarea id="text" name="text">{{presentation.texte}}</textarea></p>
</div>
<input type="submit" value="Modifier" class="inputs">
</div>
{% endif %}
{% endblock %}