FitZone/src/Entity/INFORMATION.php
<?php

namespace App\Entity;

use App\Repository\INFORMATIONRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: INFORMATIONRepository::class)]
class INFORMATION
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $TextAccueil = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTextAccueil(): ?string
    {
        return $this->TextAccueil;
    }

    public function setTextAccueil(string $TextAccueil): static
    {
        $this->TextAccueil = $TextAccueil;

        return $this;
    }
}

FitZone/src/Controller/ModifaccueilController.php
<?php

namespace App\Controller;

use App\Entity\INFORMATION;
use App\Repository\INFORMATIONRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class ModifaccueilController extends AbstractController
{
    #[Route('/modifaccueil', name: 'app_modifaccueil')]
    public function information(INFORMATIONRepository $info): Response
    {
        $information = [$info->find(1)];
        return $this->render('modifaccueil/index.html.twig', [
            'informations' => $information[0],
        ]);
    }
#[Route('/modifier-texte', name: 'app_modifier_texte', methods: ['POST'])]
public function modifierTexte(Request $request, INFORMATIONRepository $infoRepo, EntityManagerInterface $entityManager): Response
{
    if (!$this->isGranted('ROLE_ADMIN')) {
        throw $this->createAccessDeniedException();
    }

    $nouveauTexte = $request->request->get('text_accueil');
    $information = $infoRepo->find(1);
    $information->setTextAccueil($nouveauTexte);
    $entityManager->persist($information);
    $entityManager->flush();

    $this->addFlash('success', 'Texte modifié avec succès !');
    return $this->redirectToRoute('app_accueil');
}
}

FitZone/templates/modifaccueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    {% if app.user and is_granted('ROLE_ADMIN') %}
<div class="titre-Accueil">
    <h1>Bienvenue sur FitZone !</h1>
</div>

<div class="bloc-accueil">
        <form method="post" action="{{ path('app_modifier_texte') }}">
            <textarea name="text_accueil" class="form-control" rows="17" placeholder="Entrez le texte d'accueil ici..." style="width: 60vw;">
            {{ informations.textAccueil ?? '' }}</textarea>
            <div style="display: flex; justify-content: center; margin-top: 10px;">
                <button type="submit" class="btn btn-connexion my-2 my-sm-0">💾 Sauvegarder</button>
            </div>
        </form>
    {% endif %}
</div>

{% endblock %}